image: debian:stable

stages:
  - build
  - deploy

variables:
  GLUON_DEPRECATED: full
  FORCE_UNSAFE_CONFIGURE: 1
  FFHL_GLUON_VERSION: v2020.1.4

.upload_template: &manifest_and_upload
  stage: deploy
  before_script:
    - apt-get -qq update
    - apt-get -qq install -y git make gawk wget python2.7 file tar bzip2 rsync
  script:
    - mkdir -p ~/.ssh
    - 'echo -e "StrictHostKeyChecking no" > ~/.ssh/config'
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_KEY" | ssh-add -
    - DATE=$(date +%F-%H-%M-%S)
    - mkdir -p "public/$DATE"
    - cd gluon
    - mv output $DATE
    - ln -s "./$DATE" ./latest
    - find "$DATE" -maxdepth 2
    - rsync -rvhl "./$DATE" "${DEPLOY_USER}@${DEPLOY_HOST}:data/"
    - rsync -rvhl ./latest "${DEPLOY_USER}@${DEPLOY_HOST}:data/"

build_firmware:
  stage: build
  before_script:
    - apt-get -qq update
    - apt-get -qq install -y curl git libncurses-dev build-essential make gawk unzip wget python2.7 file tar bzip2
  script:
    - env | grep -i GLUON
    - git clone -q https://github.com/freifunk-gluon/gluon.git
    - cd gluon
    - git checkout $FFHL_GLUON_VERSION
    - git clone  ../ site
    - ../build-images.sh
  artifacts:
    when: always
    paths:
      - gluon/output


upload:
  <<: *manifest_and_upload
