image: debian:stable

stages:
  - init
  - build
  - deploy

variables:
  GLUON_DEPRECATED: full
  FORCE_UNSAFE_CONFIGURE: 1
  FFHL_GLUON_VERSION: v2019.1.2

generate_jobs_config:
  stage: init
  image: alpine:latest
  before_script:
    - apk add make bash git sed
  script:
    - git clone -q https://github.com/freifunk-gluon/gluon.git
    - cd gluon
    - git checkout $FFHL_GLUON_VERSION
    - git clone  ../ site
    - bash ../generate_ci_config.sh | tee ../jobs_config.yml
  artifacts:
    paths:
      - jobs_config.yml

build_targets:
  stage: build
  needs: ["generate_jobs_config"]
  trigger:
    strategy: depend
    include:
      - artifact: jobs_config.yml
        job: generate_jobs_config
